### ISSUE TITLE
Suggestions for improvement in Plugin Beds24 V2

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#129]
Hello Vince, I'm taking advantage of the fact that you are preparing the Beds24 V2 to suggest possible improvements. I do not know if they can all be implemented. I'll add what I see.

1.- There is a problem when the customer modifies the **availability through beds24**, it occurs to me that this is not possible to lend it to jomres, a possible solution is that at the time of reservation jomres check that the availability in beds24 It is not equal to zero. If that's the case, "jomers" should not offer that kind of room. 
It is essential that "jomres" can check that availability in Beds24 and in case it is 0 for a specific date and type of room does not allow the booking, otherwise it can generate overbooking easily.
It would be very good if the availability calendar would be complete by that date.

2.- There is a problem of **duplicate emails**. When booking, Beds24 sends a new reservation mail, and when that reservation is sent to jomres, "jomres" resends another new mail. I think the solution is to indicate to "jomres" that the reservation comes from beds24 do not send any new booking emails.
In Beds24 you can deactivate the sending of mails, but that is not a good idea since in the mails of new book they contain the necessary data to be able to consult the data of card.
_You could use the field "channel_manager_booking", which currently always is zero and should have a value of "1" when the reservation comes from Beds24_

3.- **Rates Synchronization**

-  When there is more than one and you make some change in the prices of some of them, **Beds24 randomly changes any of the rates you have**. There seems to be no reference to the different rates of Jomres and Beds24 to each other.

- It would be very positive to be able to **synchronize prices in both directions**. To be able to change them both in jomres and in Beds24 and that both platforms update that change. When choosing "daily prices" you should also export the minimum stay.

- Be able to choose between exporting the available rates in jomres at "daily prices" or at "rates" in Beds24.

4.- When the reservation comes from Jomres the **"Referer" field of Beds24 appears empty**. To avoid this you would have to create a new hidden field in the reservation form called "referer". It would be nice if the content of this field can be customizable and each user can indicate what they prefer.

5.- **The booking that create in Jomres appear with price 0 in Beds24**.

6.- In the list of Jomres bookings **is not known those that are from Jomres and those that come from the OTAS**. You can take advantage of the "referer" field of Beds24 and that this information appears in the summary of each reservation. It now appears as the origin of all bookings "internet".

**Comment by JuanGarciaG** [comment]
7.- If you activate the commissions, add commission to all bookings. Those that are made in jomres and those that come from Beds24 (therefore those that come from the OTAs). Should not be, commissions only be applied to bookings made through jomres.
It should be noted that the commission was not added if the referer is not the one indicated in point 4 (ie jomres).

**Comment by JuanGarciaG** [comment]
Hello Vince, we have several clients reporting continuous synchronization errors between Jomres and Beds24.
Do you have any idea when the new V2 version of the Plugin Beds24 may be active?
We no longer know how to respond to our customers and it would be very convenient that we could give them some idea of time.

Greetings.

**Comment by jomres** [comment]
> 1.- There is a problem when the customer modifies the availability through beds24, it occurs to me that this is not possible to lend it to jomres, a possible solution is that at the time of reservation jomres check that the availability in beds24 It is not equal to zero. If that's the case, "jomers" should not offer that kind of room.

That would be a bad solution, as it would significantly slow down the booking form. I think the correct solution is to ensure that Beds24 updates Jomres when availability is adjusted in Beds24. Currently the only Beds24 -> Jomres communication is booking update notifications, where Beds24 tell Jomres that a booking has been made. When it receives this notification, Jomres calls Beds24 back to get the details of the booking. I anticipate that V2 will allow much more flexible communication. 

As I´m sure you've read, V2 is being built with tight integration of the REST API functionality. Put simply, each manager will see REST API connectivity information (unique to them and that site) in their configuration page and they're encouraged to enter those details on the Beds24 account page.

Once this is a reality, then I'll be able to extend a companion API Feature plugin that is being worked on in parallel with the new Beds24 plugin. This will enable Beds24 to ask me for corresponding functionality that allows their service to directly update Jomres, including activity that it not currently covered, like availability changes. I expect to do this once the basic V2 rewrite has been done and is undergoing Alpha testing.

> 2.- There is a problem of duplicate emails. When booking, Beds24 sends a new reservation mail, and when that reservation is sent to jomres, "jomres" resends another new mail. I think the solution is to indicate to "jomres" that the reservation comes from beds24 do not send any new booking emails.

There's code to prevent guest notification emails from being sent if it's a Beds24 booking, it´s possible that you´re seeing manager notifications, which should still be sent out ( IMO ), however let's revisit this later during Alpha testing.

> 3.- Rates Synchronization

> When there is more than one and you make some change in the prices of some of them, Beds24 randomly changes any of the rates you have. There seems to be no reference to the different rates of Jomres and Beds24 to each other.

Check this once Alpha has been released. V2 is effectively a complete rewrite, very little V1 code has made it´s way into V2 and this may well not be an issue. You're correct that there is no reference between the Jomres and Beds24 tariffs, and there probably never will be. They're two significantly different systems.


> It would be very positive to be able to synchronize prices in both directions. To be able to change them both in jomres and in Beds24 and that both platforms update that change. When choosing "daily prices" you should also export the minimum stay.

See above about the REST API. One of our current tasks is to modify how tariffs in Jomres are modified, encapsulating the current, old code in minicomponents into classes. Once this is done, then I'll be writing api features so that remote services such as Beds24 can make those changes remotely.

> 4.- When the reservation comes from Jomres the "Referer" field of Beds24 appears empty. To avoid this you would have to create a new hidden field in the reservation form called "referer". It would be nice if the content of this field can be customizable and each user can indicate what they prefer.

See https://www.beds24.com/api/json/setBooking there isn't currently a feature to send a referred to Beds24 when creating bookings and sending them to Beds24. It would help if you could ask Beds24 to expose this via their API.

> 5.- The booking that create in Jomres appear with price 0 in Beds24.

Check it when Alpha testing, my test bookings appear to have prices set.

> 6.- In the list of Jomres bookings is not known those that are from Jomres and those that come from the OTAS. You can take advantage of the "referer" field of Beds24 and that this information appears in the summary of each reservation. It now appears as the origin of all bookings "internet".

We already have a referrer field, but I don't think it's shown by default, I'll check.

> 7.- If you activate the commissions, add commission to all bookings. Those that are made in jomres and those that come from Beds24 (therefore those that come from the OTAs). Should not be, commissions only be applied to bookings made through jomres.

I agree.

**Comment by jomres** [comment]
> Do you have any idea when the new V2 version of the Plugin Beds24 may be active?

I am *hoping* to have the first Alpha version available sometime in the next couple of days. Everybody with outstanding Beds24 related tickets ( including you ) will receive an invitation to work with me on improving functionality once I've done some more internal testing.

**Comment by JuanGarciaG** [comment]
Hi Vince, thanks for the info. I'm glad to know that it is short.

With respect to point 4, I believe that if the field exists to include the "referer". I have tried and it works. I attach two screens for you to check.

> See https://www.beds24.com/api/json/setBooking there isn't currently a feature to send a referred to Beds24 when creating bookings and sending them to Beds24. It would help if you could ask Beds24 to expose this via their API.

Beds24 may also be advised not to notify the customer of the new reservation so that no duplicate emails will be issued.

![setbooking json 2017-03-27 13-37-39](https://cloud.githubusercontent.com/assets/24232042/24354667/0b2723de-12f3-11e7-9ffb-df2b8cf9aa85.png)
![beds24 com control panel 2017-03-27 13-40-30](https://cloud.githubusercontent.com/assets/24232042/24354671/11520e90-12f3-11e7-8577-c8f26a21a84c.png)

**Comment by jomres** [comment]
Awesome, thanks for the feedback.

**Comment by jomres** [comment]
Addendum : 

> It would be nice if the content of this field can be customizable and each user can indicate what they prefer.

For now I'll just populate this field with "Jomres", sending referrer information via the booking form requires some changes that I'm not ready to make yet. This, IMO, is more pertinent to when we start working on the new booking engine later this year.

**Comment by JuanGarciaG** [comment]
> 1.- There is a problem when the customer modifies the availability through beds24, it occurs to me that this is not possible to lend it to jomres, a possible solution is that at the time of reservation jomres check that the availability in beds24 It is not equal to zero. If that's the case, "jomers" should not offer that kind of room.
> That would be a bad solution, as it would significantly slow down the booking form. I think the correct solution is to ensure that Beds24 updates Jomres when availability is adjusted in Beds24. Currently the only Beds24 -> Jomres communication is booking update notifications, where Beds24 tell Jomres that a booking has been made. When it receives this notification, Jomres calls Beds24 back to get the details of the booking. I anticipate that V2 will allow much more flexible communication.

The problem I see with this point is that all of the customers working with Beds24 work with the availability field. It is a field that allows manually adjusting the availability of each room without having to resort to "Black Bookings" or Room Locks. The truth is that it is very comfortable and fast and therefore all customers use it.
In jomres I think there is nothing like it. And I see it impossible to convert the availability of Beds24 in Jomres Black Reserves.
That's why I told you to make an inquiry to Beds24 when the reservation is made. This can be done through the function "getAvailabilities JSON". This is a quick query that I do not think will slow down  the booking process. Jomres could check that the availability is higher than the number of rooms requested and only in that case allow the reservation.
This is crucial to not have Overbooking. Jomres must know at all times the real availability of each room.
This solution is not completely perfect because the availability calendar may not reflect reality if the user of Beds24 manually modifies availability, but it is essential to avoid the possibility of having Overbooking.

**Comment by jomres** [comment]
I understand the problem, however as you say there's no easy solution within Jomres as it stands.

As you know, we are planning a new booking engine ( it has had to take a back-seat because I wanted the REST API functionality to be significantly complete first, and the V2 of this plugin helps me to put relevant code into place) and I think that an Inventory setting as you are referring to would be best placed there.

So...I'm aware of what you want, but it will not be in the V2 plugin. Perhaps I can think of another way around it.

**Comment by JuanGarciaG** [comment]
Hello Vince, Do you see much problem in making a query "getAvailabilities JSON" when a reservation is made ?. If the system performs this query only in case the property is working with Beds24 I do not think it would slow down the process a lot. Jomres would only allow the reservation if there is more availability than requests for reservations.

At least it would be a temporary solution until the new booking engine was ready.

If we fail to find a solution, I think that much of the benefit of working with Beds24 would be lost. There is a real risk of generating Overbooking.

But if you can think of something better, great. I, with your permission, will continue to investigate if I can think of another idea.

Thanks for your attention.

**Comment by jomres** [comment]
> Do you see much problem in making a query "getAvailabilities JSON" when a reservation is made ?

Yes. They're two completely different engines, they work very differently therefore it would not be as simple as asking Beds24 if N rooms of X type are available.
