### ISSUE TITLE
NFR: Jomres<->Jomres Integration mirroring property (syncing booking data, pricing rules, etc)

### ISSUE THREAD

**Issue by NZGRUMARI** [WoollyinWalesIT/jomres#156]
**What? Mirroring property **(syncing data)**  like bookings, pricing rules, in two jomres installations**

**Why?** Mind blowing possibilities for collaboration across Jomres platforms without channel manager as a middleman. Sometimes the two jomres installations can belong to the same company, prefering to keep two different customizations of Jomres  working with different users, markets, etc,  on the same property. This can happen for many reasons. 

Or it could be two jomres installations belonging to different owners who want to collaborate commercially without middlemen on a given property, and cannot share the same jomres installation for that

**How?**
A new plugin that would enable one Jomres installation  to share a property with another Jomres installation in the following way: 
Once a property is selected for sharing, we assign the other/s Jomres installations that will be able to replicate that property with its pricing rules etc. Both Jomres installations will be able to make bookings on the property.

**Comment by jomres** [comment]
I already have a lot of code that can do this sort of thing, however if I were to release it, it wouldn't be part of a normal Jomres license, it would have be to something you'd have to pay extra for.

**Comment by NZGRUMARI** [comment]
Hi Vince,

Is very good news, what sort of payment are you thinking of?

I guess that in your plugin you can control how many jomres installations
can share a property if they have the same Jomres license key very easily I
guess,  and calculate your extra payments in proportion, and you can charge
differently if they share one property or share 10 or 1000 as well.

I guess that your fear is that people can use this in a way that harms your
Jomres licence revenue? The only reason that I can think of your fear, is
if people having 30000 properties want to find a way to escalate for free
putting additional jomres installations, which obviously is not my case,
but I would understand that you would want to prevent that from happening.

Other that that, at the moment I cannot visualize any other situation that
would harm you, I can only see good things for you.

Jomres would lever that new capability to reign on competing products, and
would become customizable beyond any dream, in complex customization needs
due to diversity of users, target audience, etc....

Even for increased reliability, one could imagine to get two servers
running so that if one went down the other would be able to take bookings

Cheers

Juan

**Comment by jomres** [comment]
I'm not worried about people taking revenue, it's just that there aren't enough people asking for the feature to make it worthwhile, at the moment. Features are all very well, if people will use them. If there aren't enough people using them then it's pointless.

**Comment by NZGRUMARI** [comment]
OK maybe people once they see this, they become interested, to me this is
much more the a feature, it is a super super feature. Hey guys are you
interested :)?

**Comment by voyagee** [comment]
Welcome Vince! I support the idea of data synchronization according to the principle Manager of the channels between remote sites, for Example between JomresPortal and JomresHotel

**Comment by cakipoduka** [comment]
I like idea.

**Comment by benchFairyTV** [comment]
How many people expressing their interest in the extra feature would constitute a decision being made to build it?

**Comment by voyagee** [comment]
I welcome the discussion! I'm sure glad that our ideas find support among users of Jomres. Mr. Vince despises your code, it's probably right - because what good is code to be free? Of course pricing is the prerogative of the creators code and I'm not too worried. Whatever the price was, such a purchase will benefit (I mean buy the code of the plugin to synchronize data between different projects in Jomres) and not require time to develop.

Mr Vince, are You asking - how many people will be using? They say that it is pointless to do something that will not be used. This is what I think You're right. The meaning of "to collect signatures" for the creation of Lagin is lost if You have multiple users. But I think that Jomres much more users (subscribers) than just a few. 

We (the subscribers Jomres) could unite some of the projects into a single cluster with a common base of properties and mutually beneficial conditions of their retailers. I propose not to wait until completion of collection of signatures in favor, and send newsletters by email to subscribers Jomres polling/voting. Suitable?

**Comment by aadz1** [comment]
This feature sounds good to me too.

Ideally, it would also be nice to be able to select what information (from all listings in your base/primary installation) gets copied over to other Jomres installations that are secondary installations.

For example, if I only wanted to replicate specific information to the secondary installation such as only images and a brief description for all listings - so basically have an options panel in the primary installation's plugin that allows you to select which modules, tabs, etc., get replicated to the secondary installation.
Also, what if I wanted to only display listings in the secondary installation that individually link to each listing in the primary installation (so the secondary installation is basically just a page for links, maybe for a specific town only, etc.).

Doing a one-to-one/one-to-many replication might actually be possible via the Jomres API, when done through the [Zapier Developer Platform](https://zapier.com/developer/) but I believe we'd need more endpoints. Endpoints for /users (property managers), /subscriptions & possibly other endpoints for revenue generation (so we can read, create, edit & delete).

**Comment by jomres** [comment]
Absolutely we do need more endpoints. This is an ongoing process, I add them when I have time, but sadly I don't have a lot of time at the moment :(

I had a look at Zapier, I quite like it but I don't think that it's needed in this instance, everything could ( and should ) be done within the Jomres codebase. Not because I don't trust third parties, but because it's an unnecessary step.

**Comment by aadz1** [comment]
Hi Vince,

I completely understand your time constraints & not wanting unnecessary steps. The reason I mentioned Zapier is because I actually want to allow third-party applications (already on Zapier) to trigger actions in my Jomres installation.

For example, when a user submits a form (with specific data I request) then a property manager is automatically created with a listing in Jomres. This is only one example but I've got many other ways I'd like to put a completed Jomres API to use.

Would like to use automations to cut out a lot of unnecessary manual work (for my specific scenario) but I think others would also like the automation possibilities once they see the API's capabilities.

**Comment by jomres** [comment]
Build it and they will come.

Only, the bit they missed was "But slowly!" :D 

Yes, 100% with you on the whole automation thing there. The _potential_ is significant.

**Comment by aadz1** [comment]
Thanks for listening. I also think there's a ton of potential for your API - especially when people figure out how best to use it.

Potentially a good marketing play too, by advertising all the apps that Jomres has the potential to work with (via integration platforms like IFTTT, Zapier, PieSync, etc.).

**Comment by jomres** [comment]
Just as an update to this, so far this thread has had 6 repliers, plus a similar one on the Jomres forums yesterday, so 7 in total.

Given that integration functionality, a la the Online Booking Network, is a significant amount of work then I'm sure you can see that releasing something like the OBN code would result in a package that would cost something like 1+k euros per person per year to make it viable. There simply aren't enough people interested enough in it at the moment. If there were, I'd definately be up for it, but right now there isn't.

**Comment by wordskill** [comment]
It makes more sense to think of it in terms of marketing, and bolstering your current model.

The current primary Jomres model is for integrators to be approached by property owners who already want a booking site, or for the integrators to approach the property owners and suggest that a booking site would benefit them (as opposed to simply relying upon hosted services such as Airbnb).

Enabling mirroring between portal and standalone Jomres sites would give your integrators a far more effective way to generate interest and familiarize potential site buyers with Jomres:

An integrator could set up a free portal site within his city, hand out free listings to give property owners a taste of Jomres, then later follow up with the offer of a standalone booking site which, crucially, would not require additional administrative overhead from the property owner.

The pitch would be something along these lines:

"You are already maintaining a listing and calendar on our city site, and that is bringing you some bookings, but now you can ALSO have a standalone site, under your own domain and with your own added content (blog, guides, videos etc) which, over time, will have a far higher chance of ranking higher than the corporate giant when users search the name of your business. You will be able maintain more control over _your_ business as your regular clientele and reputation grows, and you won't be subject to the future financial needs of ludicrously overvalued companies such as Airbnb".

Making Jomres more profitable for integrators benefits you indirectly, insofar as integrators doing well will reduce subscription churn, but I don't suppose that prospect would be enough to make this feature financially viable for you. Instead, I think it would make sense to create a model in which you deliver this functionality and marketing model to integrators for free, but charge a per-site license fee for each standalone site which is spun-off from a city portal in this way.

As opposed to creating a thousand-Euro-per-year barrier which immediately rules out the vast majority of Jomres integrators, make it something that the property owners pay, maybe €10 per month, in addition to whatever the integrator is charging them for creating, hosting and maintaining their site.

Just to be clear, this per-site fee would have no bearing on the integrators' existing right to create as many Jomres sites as they want, it would only relate to this one feature, which would be extremely useful to integrators, winning them clients they would otherwise never get, and the ongoing fee doesn't come out of their pocket anyway. I'm sure that everyone would be delighted with that.

More importantly, it would give integrators a concrete incentive to pour time and energy into city portals, which will raise the overall profile of Jomres, attracting more integrators.

If an integrator disappears or drops out of the business for any reason, your existing billing relationship with their abandoned clients would make it far easier for to offer your own future hosting and maintenance services, if any, to them.

If you had major integrators in mind, to whom you figured the feature would be worth one thousand Euro a year upfront, well, presumably such whales would be banging out enough sites to earn that much in €10 monthly fees, especially as time goes by and they accumulate more clients - they would only need 8 clients paying €10 per month to return one thousand Euros per year to you.

You also get all the minnows which, I'm guessing, would result in far more end-user clients overall.
