### ISSUE TITLE
Room picture should hold the gallery

### ISSUE THREAD

**Issue by HDelfs** [WoollyinWalesIT/jomres#172]
Hi Vince,

Check https://www.altodalua-algarve.com/en/rooms.html
if I click on a rooms picture it only shows the first picture. Would be nice if the gallery with all available pictures is shown. 
I would not expect to have more pictures of a room shown when clicking the Availability-button. ( which should not be visible if I didn't release the availability calender to webpages visitors.)
and it is two much clicks to access easy information.

**Comment by alibarthi** [comment]
We won`t add this to the core, at least not for now, because the slideshow won`t load if the rooms tab is hidden when the page loads. Please open a ticket and mention this issue and i`ll tell you what code to edit and what to add to add this feature. However, like i said, it won`t work if the rooms are displayed in a property details tab. If the rooms are displayed on their own page, no problem, it`ll work fine.
