### ISSUE TITLE
Feature request: Price rule for [holidays], [group of nights], [packages]

### ISSUE THREAD

**Issue by fabio-n** [WoollyinWalesIT/jomres#206]
This suggestion aims at solving one of jomres' most missed features in the pricing system, when compared to other booking systems: the ability to force a group of nights to be sold together (like a holiday, new year, or even you want to force guest to buy the whole weekend: fri+sat nights). This restriction is available in other booking systems, and also in Beds24 channel manager(where it is called a "rule"). 
I tried to build this idea with the minimum impact to the Jomres logic and interface. 
So the simplest solution I see is:
1.	Add a new feature to micromanage tariffs: "restricted nights" (should have an on/off switch at the top of the tariff, and a Y/N toggle in each night)
2.	For any night marked as restricted, do not allow a booking to have either the checkin or checkout date at those restricted nights. This means the hotel would not show available in the search list, if either the selected checkin or checkout dates of the search matched any restricted night of the hotel. An improvement would be to show a message "some hotels are not shown in this result because your arrival or departure date fall inside a special period. Please try different dates to see more hotels."

Note that in this idea, the property manager does not need to mark the 1st night of the special period as restricted. Examples:

If you have a national holiday on Monday, and you want to force guests to buy [Fri, Sat, Sun] nights, you should mark as restricted the [sat] and [sun] nights. This way guests would be able to checkin or checkout on Friday (for guests leaving just before the expensive holiday), but would not be able to arrive or leave in the middle of the holiday period.

Likewise, if you have a hotel that is only busy during the weekends, and you want to avoid those guests that only want to book one night, you can mark all Saturdays of the year as restricted. This means that nobody would be able to arrive or leave on Saturday. They would need to checkin on Friday or before, and checkout on Sunday or after.

Note that this setting can and should be exported to beds24 as a "booking rule" to ensure the same will apply to all the channels updated by beds24, however to match the beds 24 data format you need to include the first night in the Beds24 rule.

This is a very important need for most hotels in the world. In my area there are many holidays per year, which most hotels sell the period as a package.

Below is my interface suggestion, it is an edit to the Micromanage tariff page. Please note:
1.	The [Enable restricted nights] switch on top
2.	The toggle [Y/N] switch in each night
3.	The [set restricted nights] option in the combo of the "multi-night updater" at the bottom. If this option is selected, the value fields should accept only Y or N. Note that if one weekday is left blank, it does not mean N, it means "do not change"
![restricted-nights](https://user-images.githubusercontent.com/10897751/29553948-bc231db8-86f3-11e7-8569-b38ec726eb65.jpg)

**Comment by tedsanford** [comment]
After spending a lot of hours testing and figuring out how this system works (it is very complete and sophisticated) as I research the best option for a portal business, I was trying to configure prices for special periods (national holidays). I tried minimum nights, multiple overlayed micromanage tariffs, and other configurations. I thought I was missing something, because nothing would acheive the ideal result, and then I found this feature request (which confirmed my suspicion that Jomres is unable to sell a "package of nights"). I would like to UPVOTE IT. This is much more important than some "marketing/layout" features that the system already has. Without a way to price correctly the hotels, I can't convince hotel owners to join my portal. The suggestion above mimics how [booking.com] works. It is the single missing element for me to use Jomres, because in my area there are many holiday dates where hotel owners sell the period as a package of several nights. Aside from this important/urgent missing element, the system is fantastic.

**Comment by joniale** [comment]
You are suggesting a "soft" black booking. That is, users should be able to block national days or defined days to not be check-in check out days. However, these soft black booking do not affect the availability of the accommodation. I will vote for this! .
