### ISSUE TITLE
Randomized pictures for towns and property

### ISSUE THREAD

**Issue by SentenzaFree** [WoollyinWalesIT/jomres#222]
It would be good Idea to randomize the town and property pictures in frontend up to 15 pics.

**Comment by jomres** [comment]
I'm going to be honest, I don't see a value for this. 

I have ( once again ) been house hunting because my rental contract has expired. Finding a new house has required searching a variety of sites such as fotocasa etc and the real estate manager's habit of using the same images on multiple sites has proven very useful in allowing me to mentally filter out those properties I have already seen.

If the "main" property image is constantly randomised, potential guests would find it much harder to bookmark in their minds those properties that they want to return to, or have dismissed  as unsuitable for them.

I think a randomisation option would be counterproductive. Of course, you can always customise the jomres_media_centre_images.class.php class to achieve the desired results. This manual page will help you to do that in an upgrade safe way 

http://www.jomres.net/manual/developers-guide/52-customising-jomres
