### ISSUE TITLE
stripe payment available for subscription

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#232]
Bonjour, Hi, 
It would be advisable to be able to cash the subscriptions directly on the account stripe of the owner of the site, without having to utlise obligatorily paypal

In addition, a stripe module to make SEPA bank debits on these subscriptions may be useful for some of us.

Jerome

**Comment by JuanGarciaG** [comment]
Since Stripe and Paypal can not coexist, I think the ideal is that the Site Manager can assign Paypal or Stripe to each of the establishments. In this way we could work by commission or subscription in a much more flexible way.
Currently you can only choose one of the two forms of payment for all establishments.
I think it is essential to be able to assign to each establishment an independent form of payment. There are establishments that prefer to pay the subscription or commission through bank transfer, while others may prefer paypal or stripe. All these forms of payment already exist in jomres, but I think they could be better used by giving freedom of choice to each establishment.
With all this I mean the payments between the establishment and the Site Manager.

**Comment by jomres** [comment]
Insufficient support for feature request.
