### ISSUE TITLE
Discount for people who booked on secound or third time

### ISSUE THREAD

**Issue by natanzi** [WoollyinWalesIT/jomres#237]
Dear Vince,
As you know discount is good feature for impress the passengers so, I suggest add this feature for jomres:
If somebody got reservation for second time or third time, system can apply discount for him...
For instance: my user in jomres  matched with this scenario and I want to got my second reservation ,so I got discount ...
first time: No discount
second time: 10%
third time: 15%
BR

**Comment by JeromePayan** [comment]
it would seem interesting if the discount can be applied to all properties of the website (portal), no matter the manager of the property

**Comment by ReneCB** [comment]
As we already have the option to issue "discount coupons" (under "Settings") in Jomres, I am not sure if this feature would help me/my landlords a lot. Even if some landlords I work with would maybe agree with a single x% discount for again booking customers (I think most would not see a reason to always further increase this discount with each further booking), there would still be others who would not want to give discounts at all (because again booking customers normally anyway come back as they liked the accommodation/their stay so much that this and not a minor discount is the (main) reason they come back again and they see this discount as avoidable loss). So I think every PM would have to decide on a property by property basis if he wants this or not in case this feature will be implemented (or to implement both cases). Still in my opinion there are other features requests that have a higher priority for me.
