### ISSUE TITLE
Provide Pageview Plugin

### ISSUE THREAD

**Issue by thleh** [WoollyinWalesIT/jomres#246]
In the jomres installation there is a table called jomres_pageviews. In older jomres version (at least until v 9.7.3) this table was populated during the core component.

It would be nice to gather that data again. 

The additional Statistics Plugin try to select data from that table too.

But please take care of the IP-Adress. There should by a way to anonymize the value (only save the first 2 parts of an ip adress --> 192.168.0.0 instead of 192.168.74.11).

Thanks 
Thomas

**Comment by jomres** [comment]
Pageview Recorder plugin should be available in the Jomres plugin manager now Thomas.

**Comment by thleh** [comment]
Hi,

thank you for the very fast implementation.
I checked the plugin but i think there are 2 issues:

1. It's triggered to offen. e.g. i found 2 entries for task viewproperty when i click it one time in the browser.
2. there are a lot of empty (task is null; property_uid = 0) events. That can be skipped.

Can you please check this ?
Thanks Thomas

**Comment by jomres** [comment]
I've updated the plugin so that it doesn't trigger on ajax calls, so update it please.

I'm not going to skip the empty tasks as other people might want to capture that information. Instead I recommend you either make that modification to the script yourself, or you filter those rows out in your own statistics apps.
