### ISSUE TITLE
Usability issue: Hide "check availability calendar" button on booking form site if “show the availability calendar inline” is set to NO

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#255]
Dear Vince and Aladar,

In case that a property owner does not want to show the availability calendar inline (Settings -> Property Configuration -> Property details page settings) it would be very good if the "check availability calendar button" on the booking form site would not be displayed (which in this case leads to an emptied popup without calendar and might make the users think that the accommodation is not available).
 
Maybe you could consider a relation there so that this button + the text on top is not displayed if “show the availability calendar inline” is set to NO. 

Another option could be to display a text like 

"Due to data privacy the owner of this accommodation does not publish the complete availability calendar for this accommodation. If you enter your arrival and departure date, the available rooms for this accommodation for this period are displayed below under Available rooms." 

in the popup that opens if you click on "check availability calendar button" on the booking form site. 

Best wishes
Rene

**Comment by jomres** [comment]
https://github.com/WoollyinWalesIT/jomres/commit/3dc4511e5f80d02189b093f15d2898274e4379eb

The current Leohtian dobooking.html file in /templates/jr_leohtian/html/com_jomres would need to be manually modified to use this option Rene. 

Note, I have not modified the show_property_calendar task to honour the setting so in theory if the guest knows that the server is Jomres then they can still call the show_property_calendar task with the correct url string. If that bothers you then you would need to create your own copy of j06000show_property_calendar.class.php and get it to check that value of 

$mrConfig[ 'showAvailabilityCalendar' ] == '0'

and just "return" if true. I won't make that change in the core because it's conceivable that somebody might simply want to disable the calendar from showing in the booking form & property details page but show it elsewhere.

If you are  going to modify j06000show_property_calendar.class.php then please note the advice on this page : http://www.jomres.net/manual/developers-guide/52-customising-jomres

**Comment by ReneCB** [comment]
Dear Vince,
Thank you very very much for including this so quickly in Jomres 9.9.20 and for the further explanation.
I am looking forward to installing Jomres 9.9.20 
: )
Best wishes 
Rene
