### ISSUE TITLE
property_uid used from session regardless of the view from which the request was sent

### ISSUE THREAD

**Issue by JadMakhlouta** [WoollyinWalesIT/jomres#274]
I am writing here about an old problem we are facing and wanted to inform you about. In many of the backend views for receptionists and property managers, the user can perform updates while the view has no property_uid paramter/input in the request; however, the property_uid is being deduced from the session usually by calling getDefaultProperty(). This works well most of the times. But consider some catastrophic cases that we faced. 

Let's assume the manager account has access to 2 properties and the user called business_settings task to update some field in the "Property Configuration". Before completing the task, he needed to perform a booking to another property to which he has access so he opened in another tab a view for that other property and after completing the booking he returned to the previous tab and modified some field. Now when he presses save he is actually not updating the settings for the property he intends to update; it is the case that the default property in the session has been modified after he performed the booking on the other property and while the view in the first tab is for one property, the changes are affecting the other property and spoiling it. 

To solve this issue all update/edit/save tasks must have property_uid passed to them and not deduced from session. Otherwise there is a real source of confusion that the normal user won't understand. Currently to workaround this, I am creating users to have access to only one property. But this is not always convenient.

The solution is theoretically easy but needs comprehensive changes for minor sections in most templates and php files: to add a hidden input containing the property_uid in most views and reading it from php instead of getDefaultProperty().

**Comment by ReneCB** [comment]
I totally agree with JadMakhlouta. I would be happy if you could eliminate the danger that one property is overwritten with another by a receptionist or property manager who manages more than one property and has more than one tab open (from our work we know how often we have multiple tabs open to compare settings or to copy passages). We already had a few days extra work to fix such cases. Worst case the whole property description text is lost and must be re-written (and in the receptionists / property managers this is our/the portal operators business as they regard it as a technical insufficiency). Currently we always take a local text copy of the property description texts (and in all languages) for all receptionists or property managers who manage more than one property in order to be able to react quickly if this happens again. If you find the time to solve this this would be great.

**Comment by JeromePayan** [comment]
Hello,

This is actually a problem that I have seen many times, being connected as a property manager.

If I open a property in jomres to make some changes, as a property manager (or super property manager) and I open another tab in the browser to copy for example a description of another property, then it there is a crash of information from one property to another. We often find ourselves with two identical properties (name, description ...). Other configurations like prices, layout seem to be spared.

**Comment by jomres** [comment]
I have an idea, one that I'd like you folks to test for me.

Open cms_specific_urls.php

I assume you're all using BS3, therefore you will find that file in \jomres\libraries\jomres\cms_specific\joomla3

After L39 put this : 

if(isset($_REQUEST['property_uid'])) {
  $jomresItemid .= "&thisProperty=".(int)$_REQUEST['thisProperty'];
}
else {
  if(isset($_REQUEST['thisProperty']))
    $jomresItemid .= "&thisProperty=".(int)$_REQUEST['thisProperty'];
}


Whenever thisProperty is in the url, Jomres is forced to change the currently active property to whatever the property uid is. I'm thinking that if we do this this way, we should be adding the property uid to every url, even if the property uid is different in each tab, I have a gut feeling that this will work and more importantly, it'll be secure.

Take your time, as you know 9.11.2 has been released so there's plenty of time before the next version.

The jomresItemid variable is just used because it's a convenient place to put the rest of the code.
