### ISSUE TITLE
from Nightly to Final - version number in extension's database is not getting updated

### ISSUE THREAD

**Issue by paul2011** [WoollyinWalesIT/jomres#287]
I'm using Joomla.

When I update to Nightly, just to see the new changes and how they work, the version number in the extension's database (component, com_jomres) is not updated but everything works great!

So when the final version comes out and I update to it, the version number in the extension's database is not getting updated.

So each time I go to my Joomla site with Jomres, it's asking me to update to the new version of Jomres but the new version is already installed.

What I have to do when this happens is go to my database and change the old number: 9.10.2 to the new number: 9.11.0 and all is good.

This doesn't happen when I just update to the next version of Jomres without updating to Nightly first.

I wonder if anybody else is having the same problem?

Thanks

**Comment by jomres** [comment]
The version in J comes from the cms specific plugin's xml file, which isn't updated until I build the file hashes just before release. 

New versions of the nightly often require that plugins be updated too, so internally for example I would make the version of Jomres the new version. This means that I can deliver those updated plugins from the plugin manager without affecting users on the Master, stable version. 

That's why in J even if you've updated to the Nightly, the version in J remains at whatever your last version was.

After installing the Nightly, if you think that there are any table changes ( check https://github.com/WoollyinWalesIT/jomres/tree/master/database/updates to be sure ) then you should run the Database Integrity Check page in Admin > Jomres > Tools. Among other things it'll update the db version of Jomres to whatever the newest version of the Nightly is.

**Comment by paul2011** [comment]
Great, thanks!

Didn't think about trying the Database Integrity Check. I'll try that next time.

**Comment by jomres** [comment]
De nada
