### ISSUE TITLE
Email validation problem

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#295]
When I try to make a booking with a registered user it always gives me an email validation error (although this is correct) and redirects to the "edit_my_account" page.

The problem is in the dobooking.php file:

if ($ thisJRUser-> userIsRegistered &&! $ thisJRUser-> userIsManager &&! filter_var ($ guest ['EMAIL'], FILTER_VALIDATE_EMAIL)) {
jomresRedirect (jomresURL (JOMRES_SITEPAGE_URL. '& task = edit_my_account'), jr_gettext ('_ JOMRES_CANNOT_BOOK_INVALID_EMAIL', '_JOMRES_CANNOT_BOOK_INVALID_EMAIL', false, false), 'alert-danger');
}

If I delete this conditional, it works perfectly.

**Comment by ReneCB** [comment]
To be honest I would be happy if there would be no check + message (“Email address: Sorry, that email address is already in use. If this is your email address, please ensure you have logged in before attempting to book.”) if the user is already registered when he want to book again. 
If a returning user does not immediately have his login details by hand this always will result in an obstacle / less people booking. Especially as I am often facing redirection issues upon login (the user is redirected to the homepage) and the user then has to navigate back to the property, add the room, …
Great would be a functionality where the email address is validated and for returning users (guests; maybe not for managers) the booking is automatically connected with the user account of the respective user (so that he can also find all his bookings there). To be honest I would also be glad (for users/guests who book again; not for managers) if a new password email would be sent so that the guests directly have a mail with username and password upon booking if his email-address is already in use (from my opinion it cannot hurt to get a new password from time to time and this way they guests really have their login details together with their booking documents. 
What do you (Juan/Vince) think about this?

**Comment by ReneCB** [comment]
P.S.: I just had a returning customer who simply used a different email address now (after getting the message: “Email address: Sorry, that email address is already in use. If this is your email address, please ensure you have logged in before attempting to book.”) as it is too complicated with having to log in before booking. He simply used a different email address now with the result that he has two accounts now and 1 booking in each (which I cannot merge in one account now). Definitely the email-validation/the process for returning customers needs to be simplified. Please help!

**Comment by jomres** [comment]
Well, I'm happy to ditch the section that Juan mentioned, it was added to make things easier however if it's causing more problems than helping then of course it should be got shot of.

> Especially as I am often facing redirection issues upon login (the user is redirected to the homepage) and the user then has to navigate back to the property, add the room

FWIW if you use the Quick Register plugin, the login form will return you to whatever page you were on. It's not the prettiest form, however it's not difficult to make it nicer. It's also possible to insert the  Quick Register script's output into another template, such as the property header using this little used feature : 

http://www.jomres.net/manual/developers-guide/52-customising-jomres/366-including-script-content-in-another-template

That, of course, doesn't get us around the problem of registered users not getting/using their logins.

I think what we need to do is consider how dangerous it is to automatically link email addresses used by un-registered guests with existing, registered guests. The security concious part of me balks at the idea, but at the same time I'm sympathetic to your guest's problems.

What happens if naughty son/daughter decides that they want a jollie on dad's account?
What happens if a malicious actor wants to tie up a property or cause some other kind of trouble?

Now, if the property uses a payment gateway, neither of these are likely to be issues because the gateway itself acts as a kind of a gateway for the booking. Without payment it doesn't get added. 

There are, however, other problems that I can forsee.

It wouldn't be too difficult to associate the temporary booking data with a registered user once they've tried to use their email address. However there's a problem in that if I made it so that the guest's details were loaded once the email address was used then due to the stateless nature of the web, it would be trivial for the bad guy to reload the booking form to see the guest's name, address etc. That's a data exposure vulnerability that I'm absolutely loathe to add.

Rene's idea of re-sending a password reset email is a good one and bears consideration. Another option could be to have a login form popup on the page when a registered user's email is used, we could log them in via ajax. That option I think has legs.

I'm not committing to any change yet, I'd appreciate your feedback first, it needs to be discussed further.

**Comment by ReneCB** [comment]
1. Thank you for providing the solution concerning the redirection issues upon login by installing the Quick Register plugin. 

2. Concering the other topic: “That, of course, doesn't get us around the problem of registered users not getting/using their logins.” for returning customers (email-address validation in booking form).
I agree with Vince that there is a high security risk to automatically link email addresses used by un-registered guests with existing, registered guests without evaluation for properties that do not use a payment gateway.

What about the following idea for properties that do not use a payment gateway:
If a returning user fills in an already existing email address and clicks on “confirm booking” at the bottom of the booking form (the email validation will only start with this click) he will first get a popup message that his email address is already in use and that a validation mail was sent to him to confirm that he is really the owner of this e-mail address together with the promise that this is also useful for him so that the new booking can be added to his already existing account where he can find his booking history. Upon click on the email address confirmation link in this email the booking confirmation email could be sent, maybe together with a new password so that the user has it 100 % again. 

Also in the popup message mentioned above should be the option to fill in the login password directly to verify his email address if the returning customer has it available (if the user uses this option then maybe a new password should not be issued).

All this naturally only for returning customers.

What do you think about this?

**Comment by ReneCB** [comment]
P.S.:

Or just a popup with a small intro text and two options. Like:
"Dear [NAME], we are happy that you would like to book with us again. To be able to manage all your bookings together, it is necessary that you log in briefly so that the booking can be added to your user account. This also ensures that you are authorized to use the e-mail address provided. 
Please enter your password in the field below and then click on "Login" (or "Add booking to my account"). [Password field + button]. If you do not have your password (or your login data) at hand, please click on "Send password again". [Insert button "Send password again"]. 
If you click on "Resend password", the pop-up window remains open and a message appears informing you that the new password has just been sent by e-mail + a request to copy it from the e-mail in the inbox of the e-mail account and enter it in the password field above.


 "A new password was just sent to your email address [EMAIL-ADRESS]. Please copy your new password from this email in the password field above and then click on "Login" (or "Add booking to my account")."

Here is a already a German translation:
"Lieber [NAME], wir freuen uns, dass Sie wieder bei uns buchen möchten. Damit Sie alle Ihre Buchungen zusammen verwalten können, ist es notwendig, dass Sie sich kurz einloggen, damit die Buchung zu Ihrem Benutzerkonto hinzugefügt werden kann. Zudem ist so auch sichergestellt, dass Sie berechtigt sind, die angegebene E-Mail-Adresse zu nutzen.
Bitte geben Sie in dem unten stehenden Feld Ihr Passwort ein und klicken Sie dann auf "Login" (oder "Buchung zu meinem Benutzerkonto hinzufügen"). [Passwortfeld + Button]. Sofern Sie Ihr Passwort (oder Ihre Login-Daten) gerade nicht zur Hand haben, klicken Sie bitte auf "Passwort erneut zusenden"." [Button "Passwort erneut zusenden"]. 
Bei Klick auf "Passwort erneut zusenden" bleibt das Popup-Fenster geöffnet und es erscheint der Hinweis, dass das neue Passwort gerade per Mail zugeschickt wurde + die Aufforderung, dieses aus der E-Mail im Posteingang des E-Mail-Accounts zu kopieren und in das oben stehende Passwort-Feld einzugeben.
"Ein neues Passwort wurde soeben an Ihre E-Mail-Adresse [EMAIL-ADRESSE] geschickt. Bitte kopieren Sie Ihr neues Passwort aus dieser E-Mail in das obige Passwortfeld und klicken Sie dann auf "Login" (oder "Buchung zu meinem Konto hinzufügen").

If you want a different text feel free to contact me.

Best regards, René

**Comment by JeromePayan** [comment]
Bonjour !

This is a good subject to work on it ! Thanks guys

This actually poses quite a problem for the customer who tries to come back a second time.

from my point of view, simple user (I'm not a programmer) Do not reinvent what is already done on referrals such as Airbnb or booking.com, because users are already quite formatted by this type of site Internet . And it is true that the user experience at home is quite advanced and intuitive.

The customer who reserves the first time must be able to keep his login credentials on his browser

Jomres must then be able to recognize it on the second reservation and the following ones.

In case of loss of identifier or omissions, the system must be able to offer this type of simplistic popup window (without much text) to allow him to recover his identifiers by mail
![capture](https://user-images.githubusercontent.com/25484155/42418016-2a1ae356-8297-11e8-86ea-d6e35664b983.JPG)

**Comment by jomres** [comment]
Jerome,

That's more or less what Rene was suggesting.

**Comment by jomres** [comment]
Can you folks test the Nightly? You can now login at the booking form. This isn't it's final form, right now I just need to ensure that it's working as currently presented.

**Comment by ReneCB** [comment]
Dear Vince,

first of all I wish you all the best to your birthday!!!

I hope you at least celebrate tonight as you have been working on your birthday to solve the email validation case!

I installed the new nightly and found the login button next to the email address field when I entered an existing email address. I think this is a good solution.

I could log in but I got the following error message after I logged in
(I think this stems from the fact the booking dates were reset to Arrival: today – Departure: tomorrow after login):

________________________________
Sorry! An error occured while trying to process this function. It has been reported for you and we will look into it.
The booking period you have specified so far is too short to book this accommodation. The landlord of this accommodation only accepts bookings with a minimum stay of 3 nights. Please adjust Arrival Date and Departure Date in the two input boxes below this text accordingly. Currently, the booking period you specified only has the following number of nights: 1
________________________________

Apart from this the login process worked fine and I was not redirected away from the booking form but still on the booking form after login. This is fine.
Very nice also that it is enough for returning customers to just to enter their email address (that they used for the earlier booking) in the email address field (and no other field) and upon login all other fields are automatically filled out/added from the customer account. So actually it is sufficient if the returning user just fills in the email address and click on login afterwards. I like this :).

What is still missing is the option to get a new password sent when the user cannot remember his password (or has not saved it in the browser).

But altogether I think this is on a very good way! Thank you very much!

Have a nice birthday evening (and some beers now)!

Cheers and all the best for you and also to your dogs (I like the new project pups page you added to jomres.net; we also have two food inhalers supporting us),

René


Von: Vince Wooll <notifications@github.com>
Gesendet: Montag, 9. Juli 2018 17:07
An: WoollyinWalesIT/jomres <jomres@noreply.github.com>
Cc: ReneCB <rene.beckmann@outlook.com>; Comment <comment@noreply.github.com>
Betreff: Re: [WoollyinWalesIT/jomres] Email validation problem (#295)


Can you folks test the Nightly? You can now login at the booking form. This isn't it's final form, right now I just need to ensure that it's working as currently presented.

**Comment by jomres** [comment]
It's not my birthday til next month, René so we can celebrate again if you want 👯‍♂️ 

> What is still missing is the option to get a new password sent when the user cannot remember his password (or has not saved it in the browser). 

Yes, I agree. 

Yesterday I was struggling with the 11 year old problem that the already selected rooms cannot be re-selected when the form is reloaded. The solution is either to fix this (would be nice) or to use ajax to log the user in. I'm going to re-attack that today as I prefer the former solution to the latter as it has other benefits.

I nearly had a fix and then _poof_ it disappeared again. *sigh*

> Cheers and all the best for you and also to your dogs (I like the new project pups page you added to jomres.net; we also have two food inhalers supporting us),

Thank you. Gotta keep the doggy cheerleader teams involved in what we do, it's for them after all.

**Comment by ReneCB** [comment]
Fingers crossed that you find a fix today (in the near future) for the 11 year old problem without a wizard letting it vanish again ;-).

Sorry about the early congratulations (your new Jomres offer made me think it must have been yesterday…).


Von: Vince Wooll <notifications@github.com>
Gesendet: Dienstag, 10. Juli 2018 09:50
An: WoollyinWalesIT/jomres <jomres@noreply.github.com>
Cc: ReneCB <rene.beckmann@outlook.com>; Comment <comment@noreply.github.com>
Betreff: Re: [WoollyinWalesIT/jomres] Email validation problem (#295)


It's not my birthday til next month, René so we can celebrate again if you want 👯‍♂️

What is still missing is the option to get a new password sent when the user cannot remember his password (or has not saved it in the browser).

Yes, I agree.

Yesterday I was struggling with the 11 year old problem that the already selected rooms cannot be re-selected when the form is reloaded. The solution is either to fix this (would be nice) or to use ajax to log the user in. I'm going to re-attack that today as I prefer the former solution to the latter as it has other benefits.

I nearly had a fix and then poof it disappeared again. sigh

Cheers and all the best for you and also to your dogs (I like the new project pups page you added to jomres.net; we also have two food inhalers supporting us),

Thank you. Gotta keep the doggy cheerleader teams involved in what we do, it's for them after all.

**Comment by jomres** [comment]
I've battled with the room selection thing a bit more, I might be closer to a solution, but not today.

> Would it maybe make sense to move the email address field to the top of the booking form so that returning customers do not have to bother to fill out the other fields before (that will be automatically added after login)?

It's one of those things that you shouldn't need to see unless it's required. The reason I added to the text output of the "oops" message is because you will only see it when the validation failure occurs, and you'd be editing that spot at the time, typically.

The other reason was so that you people wouldn't need to modify your versions of the dobook.html template files. Users like to modify things like the booking form, and telling every. single. one of you to make that change would just piss off a whole bunch of people. This method side-steps that problem entirely.

**Comment by ReneCB** [comment]
Dear Vince, any news on this topic? It would be great to have a solution as we have the problem that users who only have one email address and have one booking rejected have immense difficulties to book an alternative when they receive the rejection email as their email address is already in use. I can see from the user account data in the Joomla backend that users normally (due to the usability problem with the login) react by rather entering an alternative email (so that they have another account on the same name) than to try to figure out how to log in and use the email address they used for the first request. At least a part of those users who have no alternative email address (especially older customers) give up and book somewhere else (and not with us).

**Comment by ReneCB** [comment]
It holds for 9.12.0 as I did not install the nightly yet on my live site (only on the test site) since the "option to get a new password sent when the user cannot remember his password" (see 6 messages above) was as far as I can remember not added yet. Also I was not sure if you want me to install the nightly on a live site (and not wait for the next master).

**Comment by jomres** [comment]
Well, I can't say I didn't try. I spent far too many hours trying to find a way to automatically send the password reset email automagically but it's not going to happen. Instead I've added a button to the popup with a link to the  password reset form.

**Comment by ReneCB** [comment]
I like it Vince! Thank you very much.

Here is a already my German translation for the text in the popup:
---------
Wir freuen uns, dass Sie wieder bei uns buchen möchten. Damit Sie alle Ihre Buchungen zusammen verwalten können, ist es notwendig, dass Sie sich einloggen, damit die Buchung zu Ihrem Benutzerkonto hinzugefügt werden kann. Zudem ist so auch sichergestellt, dass Sie berechtigt sind, die angegebene E-Mail-Adresse zu verwenden.

Wenn Sie Ihr Passwort nicht zur Hand oder vergessen haben, können wir Ihnen eine E-Mail zum Zurücksetzen Ihres Passworts zusenden. Bitte folgen Sie den Anweisungen in dieser E-Mail, um Ihr Passwort zurückzusetzen.

Passwort vergessen?
---------

Thank you very much!
René

**Comment by joniale** [comment]
Hi,
The solutions suggested are only valid for those webs that requires the user to be logged. Some webs don´t like to force the user to leave login details (our case). Therefore users only have to fill the booking form and that is all.
Many clients just want to know how the checkout process works and they don´t like to create an user account first. That flow scares many potential clients. 

Is there any solution for those webs?

A simple solution would be to offer the site manager the option to just avoid the check of email for returning users in order to force them to login first.
 In my opinion, jomres should not force the web architecture to create user accounts with passwords.
Regarding the security issue: As Vince, says if the web uses a gateway to process all the bookings (our case) that should be enough.
Please, include the option to disable the check. We are happy with the booking info associated by email and not by email and password (account).
Any idea?
BR

**Comment by joniale** [comment]
Hi,
The new GDPR law requires that the web delete all privacy data if one user request this. If you are not able to identify an user safely (only by his email), then it is a problem and it is needed something else.  Obviously, only one email is not enough to identify an user. That is because other people could use the email from other users. To identify an user as the real user owner of an email **we don´t need accounts (email + password)**. We can check that the user is the real owner of the email by using the procedure that was explained by ReneCB before.
Jomres can send **an email confirmation message to that email.** Then, the user needs to click or collect a code that can be used to continue with the booking process without the need of creating an specific account in joomla/jomres.  The same procedure can be used for a request to delete all information related to one email.
In that way, we get rid off the accounts in joomla. Personally, i consider the idea of creating dummy accounts in the different websites an old pain. Many users just provide the same password on every site and when one site is hacked this password could be a security risk for the user. We can avoid that problem by forcing the user to login to his email account using only his email password which should be a secure one and tell us to confirm his identity. Personally outsourcing the password management is a better way to handle this things. At least, should be an option that jomres shoudl consider.

What do you think?

Best regards,
joniale
