### ISSUE TITLE
Chatbot?

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#313]
I've been approached by a chatbot developer who is interested in integrating with Jomres.

The idea is that the bot would handle the initial connection, and any questions it can't answer it'll hand off to a human bean. 

Does this interest anybody?

**Comment by ReneCB** [comment]
I am not sure (especially for multilanguage installations) if the effort to implement and setup this "feature" really pays out... I think that I proactively already integrated the answers to nearly all "standard" FAQs (late check-in/check-out possible? baby cot available? transfer options? ...) in the site texts, so that we currently do not get to many questions with the same topics (= FAQs) which - as I think - would be the cases that a chatbot could handle. I assume that a great part of the questions that we receive would still be handed off to the human being. If you think I am wrong maybe you could place a link to the chatbot solution - if it is very advanced I would maybe change my mind ;-)

**Comment by joniale** [comment]
I agree with ReneCB, most of the topics to be discussed offline would be covered by the web or a FAQ. So in fact we do not need a chatbot but a simple chat or a way to connect interactively the owner with the potential user. If it is included in jomres it would be always welcomed.

**Comment by nine007** [comment]
I use tawk.to , it tells me exactly on witch page the user is on, his browsing history on the site, can create tickets for the person, a FAQ list for easy copy and paste, and its free, so don't think a chatbot is important now, other matters like channel management is on top of the list.

**Comment by JeromePayan** [comment]
I am using for Zendesk (free mode) for incoming guest... BUT i need to answer myself to guest question 
AND
using since 1 month Wishbox, to manage guest with a booking.  It's allow me through Beds24 to:
- sending an automatic confirmation email EVEN WITH GUEST FROM  airbnb, booking, expedia 
- sending an automatic pre-check-in and check-out email to update arrival time, departure time, asking the guest is real email adress, confirming number of guest....
- creating an user box information about the arrival, departure procedure, uspselling, contact number for check-in...
My last ticket about this #367 

I think this is a real feature to integrate to jomres if we want jormes to be the booking HUB management.
