### ISSUE TITLE
Login Confirmation - Feature Request

### ISSUE THREAD

**Issue by ChiliKutiAfrica** [WoollyinWalesIT/jomres#333]
If a new user tries to login and his login details was not correct, there is no way for him to know that as nothing happens after entering email address and password.  Would it be possible to add text that says you are successfully logged in or your password is incorrect?

**Comment by natanzi** [comment]
+1 is simple

**Comment by jomres** [comment]
Ok, perhaps we're thinking of different things. If you use the Jomres Quick Register plugin and try to login that way, and it fails, then you'll see a message that looks like

https://snippets.jomres.net/2018-11-12-jqdee.png

What are you seeing?

**Comment by jomres** [comment]
The issue was caused because the Jomres quicklogin plugin was being used on a non-Jomres page and in WP that was problematic, it wasn't designed to be used this way. 

The ideal end solution is to simply use the CMS's login features. Joomla has a frontend login feature, Wordpress needs (I understand) a plugin to achieve the same thing. The host CMS's login features are always going to be more appropriate to use than Jomres, the Jomres one was only ever intended to be a quick and dirty login feature whereas the host CMS's features will include access to features such as TFA if available.
