### ISSUE TITLE
Option to have different prices for the same room type in MRPs (for example higher prices for apartments on top floor)

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#337]
Hi Vince, 

I am more and more often facing the issue that landlords with an MRP want to use different prices for the same room type (e.g. 2-bedroom apartment) due to varios reasons:

- Top floor more expensive than ground floor
- Apartments are  on different standards (some renovated, others not yet)
- ...

Therefore it would be great to have the option to use different prices with the same room type. I think it would be great if I could use one basic tariff per room type and then define under "Settings" -->"Rooms" (if required) that there is a surcharge for a specific room (e.g. penthouse surcharge for No. 2). Great would be if I could configure something like +XYZ EUR for the room under "Settings" -->"Rooms".  

Currently I find no rearly good solution for this but only a workaround that is frustrating for the users (creating multiple tariffs for the same room type and writing a long booking form instruction text so that the user picks the right tariff after clicking on "details" on the booking form page ... which from my experience is not working smoothly) and is also needs careful checking by the PM (causing trouble from my experience).

It would be great if we could control the price deviation (surcharge/rebate) from the tariff for the respective room type per room somewhere under "Settings" -->"Rooms".

Happy about every +1 for this ;-)

Best wishes, René

**Comment by ReneCB** [comment]
As I am already confronted with this restriction again: 
Another option would be to add this feature under "Settings" --> "Tariffs". 
Ideal would be to add a field under "Resource/property type" where I can either check "Tariff valid for all rooms of this resource/property type" or "Tariff valid for rooms no. " + a list of all rooms of this resource/property type from which I can choose (maybe via checkboxes) for which rooms the tariff should be valid (task=edit_tariff_micromanage&tarifftypeid=XYZ). 

Happy for supporters of this feature request!

**Comment by nine007** [comment]
Good Day
I would really welcome this option. I am confronted everyday with new sign ups of properties where the person has one or two resource/property type's but have several rooms for each type and the prices for each room is different.  This would be a welcome addition.

thank you.

**Comment by ReneCB** [comment]
Vince, as I operate a portal for me the "workaround" to create other room types to solve this (option to have different prices for the same room type in MRPs) is not an option as this leads to trouble with the search filters. What will happen if I have 8 different(ly named) kind of (broken down) "2 bedroom apartments" if everybody solves it as you suggested. This would end up badly I think. If you are a guest searching for a 2 bedroom apartment, which one from the 8 options would you pick from the filter?

**Comment by nine007** [comment]
I am currently using the feature for managers to create their own room types, but I only see this is a short term solution, because the list of room types is getting too long and then we cant use the search function to search for room types. 

Many of our properties have dozens of rooms and they want only say 5 room types but each room has its own price, also to be able to group rooms under room types is the way to go otherwise we sit with a list of rooms that is too long for the browser.

Here is a great example where rooms are grouped under room types
https://www.travelground.com/accommodation/airport-lodge-guest-house/rooms

and when it comes to the booking of those rooms:
https://www.travelground.com/accommodation/airport-lodge-guest-house/book

**Comment by jomres** [comment]
>  If you are a guest searching for a 2 bedroom apartment, which one from the 8 options would you pick from the filter?

Now you know why, for years, I resisted the ability for property managers to create their own room types :)

**Comment by nine007** [comment]
Yes, I do see your point why you resisted for property managers to create their own room types, we already sit with almost 80 room types that property owners wants because they cant assign tariffs to each room, that's why we had to disable room type in the filters.

The example links I gave above are the only long term solution witch I could find, and I could see more and more sites going that approach.

**Comment by Nikos-c** [comment]
nine007, the solution to your problem is the following
As I understand your site "sells" rooms. So what you can do is to create "Property Types" (I renamed it to "Accommodation Type" on the search form) like that

Hotel (--> for rooms)
Studios & Apartments
Cottage
Villa
etc.

When a manager creates a custom room (which it can be a room, a studio, a villa etc) it should be assigned to the right "Property Type". In this case a room should be assigned to "Hotel", a studio to "Studios & Apartments" etc.
On the search form a visitor will be able to choose if he is looking fo a room, studio or apartment etc. A room is room, no matter if it is on the first or ground floor, has seaview or poolview etc
You can also create some standard (commonly used) "room types" as an administration which managers could use with out the need to create custom ones, like "Double room", "Triple room",...

Don't use the room type filter at all. It makes no sense to users.

Reagrds,
Nikos

**Comment by ReneCB** [comment]
From the discussions that we get today for this issue and some related issues I get the impression that the "tariff/price topic" is by far the most important topic that should be addressed.
See also (these are just the ones I found quickly).
#251 
#310 
#124 
#206 
I know this is a "complex" topic to touch. Also some of Rodrigo's plugins are involved (at least I directly think of the JPD discounts one). But from the by Jomre's standards quite active participation today I think that it is necessary to concentrate on that tariff/price topic. I think that it is necessary that discounts are directly visible to the customers and not only exactly calculated after the room has been added on the booking form page. The last minute / wise price feature is great but actually nearly "hidden" on the property details page (the discounts should already be visible in the search list and the property details page). The users want to see the final prices directly and maybe they do pick other accommodations that look cheaper in the search results list but are actually more expensive - but the user does not recognise this. 

Jerome is right that it would very much make sense to have basic tariff plus a field with +XY EUR or whatever currency for an extra person to have a simpler tariff creation / system. Maybe we could also solve the different prices for the same room type in MRPs topic somehow like I described above when I opened this Issue on 31 Oct: The basic tariff for a room type maybe could be altered +/- some amount for some room(s)/numbers if a field like this could be implemented in the room list. Then the filters would still be good to use. Vince, I know this is a lot for a Christmas wish but I would be glad if you could maybe somehow address this topic in the beginning of (or not too late) next year. I do not know what is top on your priority list currently and if there is a chance. But I think you would make some - as far a I can see quite active users here at github - very happy ;-).

Vince, I want to thank you very, very much for the great job again this year. It's just amazing what you have all been working on (GDPR, ...). I think that Jomres has improved quite a lot in 2018. I already wish you and all the others here a Merry Christmas and a Happy New Year 2019
Best regards
René

**Comment by nine007** [comment]
thank you Nikos-c that is what we are doing, but is still not solve the issue of assigning a tariff to a specific room/s that is linked to room types. We can have a hotel as a property type and have Single rooms, double rooms, apartments and so on linked to the the Hotel, and also have 20 single rooms, 20 double rooms and 20 apartments, and then have different prices for each of the 20 single rooms and so on.

This also creates a long list of rooms in the property details page, the solution is to group the 20 single rooms under the single room room type, like the example below.
https://www.travelground.com/accommodation/airport-lodge-guest-house/rooms

hope this makes sense.

thank you

**Comment by jomres** [comment]
I'm going to close this as the initial conversation has evolved and the room surcharge effectively resolves the main feature request. 

That's not to say that other requests don't have merit.

**Comment by JeromePayan** [comment]
yes Vince but please, do not forget that we need  the room surcharge option for entire property  too.
Merci
