### ISSUE TITLE
Right, let's get to it boys and girls

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#347]
After a Christmas where I was finally able to get some rest from the grind, I'm back and raring to go.

The features request list is huge, so can y'all nominate the most important feature that you want developed for the next version?

**Comment by jomres** [comment]
Currently I'm working on custom invoice numbers for properties.

**Comment by nine007** [comment]
good day

Hope you had a good rest, hope this new year will be good for you.

The issue that I think require the most attentions is #337 

Another reason it is important is we are looking into developing 2 channel management plugins, and they all require that tariffs must be linked to rooms.  Everyday we struggle with people listing properties with 5 or more room types, but 5 or 10 and even more rooms with different prices.  I know this is a big one.

thank you.

**Comment by ReneCB** [comment]
Welcome back and Happy New Year, Vince!

I agree with nine007. 
Option to have different prices for the same room type in MRPs (for example higher prices for apartments on top floor) #337
has a high priority for me as well as the other price/tariff related topics mentioned in the 337 discussion:

- Last Minute discounts considered directly on front page/in search result list and property details page and not only after adding a accommodation unit on the booking form site #310
- Enhanced Property List Totals - Consideration of last minute and/or wise price settings #291
- Basic pricing for renting #251

Thank you for consideration, Vince!

**Comment by jomres** [comment]
Check out Nightly, you can test this feature for me folks.

https://github.com/WoollyinWalesIT/jomres/commit/e87af098fbe7c93f3dd586addd6808b2500bfdc9

You'll need to run the database integrity check after updating to Nightly. Dev servers only for now, please.

https://www.jomres.net/manual/installation-and-upgrading-2/370-installing-updating-to-the-nightly-branch

**Comment by nine007** [comment]
Good Day

Hope all is well, thank you for your hard work, I updated the nightly and tested the surcharge, a couple of questions arise then working with it, still not sure if this is going to work or not.

1.  How do we translate this to the property owner listing their property?
2.  How do we translate this to the property detail page so that the guest can see that room 1 total cost is xyz per night, or that room 2 price per person per room per night is abc, I saw that currently it is per day, but what about per person per room?
3.  It also feels that the tariff's are split, making it difficult for venue owners to manage their tariff's in different places.
4.  A surcharge also feel like it can be a extra.

For me the easiest way is to have a dropdown select box in the tariffs page where room name is linked to the property/resource type selected, I attached a screenshot, that to me makes the most sense, its easy to understand, and its in one place.

thank you again, I really appreciate what you are doing.

![room tariff](https://user-images.githubusercontent.com/1021432/51016121-c44a3580-1577-11e9-8827-0acadb56c3d9.png)

**Comment by ReneCB** [comment]
Dear Vince,

thank you very much for your fast work and starting to work on this topic at all. I like it very much and in the most important point do not agree with nine007. I think this is well done (as a start as you pointed out yourself when you named it "Experimental feature for #337 Surcharges for individual rooms") and now it only needs a bit more fine tuning. So there could be a text explanation (maybe also with a direct link) under "Setting" -> "Tariffs" pointing out that deviations from the standard prices/tariff for a room type need to be configured under "Settings" -> "Rooms" (where actually also the "Single person supplements" are already defined for a long time; so we already have a division of some price related issues between "Rooms" and "Tariffs"; this is not brand new). 

I think this is pretty straight forward and from my point of view the most logical way. The basic prices (which I think will be also be a future topic; see "Basic pricing for renting #251") per room type are defined under "Tariffs" and the deviations from the basic tariff structure for a room type for an individual rooms or some rooms (there might be several ones(!)) are defined under "Rooms" (little suggestion: maybe better write "An additional charge that will be added to the room when booked (calculated per night)" instead of "An additional charge that will be added to the room when booked (calculated per day)" as I think most accommodations calculate with prices per night). 

The proposal from nine007 with the dropdown (see her picture above) does not solve what we wanted to achieve here as the proposed dropdown in the end will lead to more room types required again which we must not have in order to keep the filter function (search filters) the way that we do not get too much confusion there. It is very important to have in mind how the implementation of this will affect the search filters.

Nine007 is right that the division of some price related issues between "Tariffs" and "Rooms" needs some explanation and also needs to be translated to the guests/user on the property detail page. This could for instance be done by considering this in the prices range under "Room Types". 
![room-type-price-range](https://user-images.githubusercontent.com/35758332/51018389-b1376580-1577-11e9-9657-b4be89458151.JPG)
Also the Enhanced Property List  Totals  plugin could maybe be adjusted to display a price range. Also the price range could be displayed in the property header (from ... to ... EUR per room type if the Enhanced Property List Totals plugin is installed (which I like very much but which needs some improvement)). 

The final prices for each room will be visible on the booking page also. I am sure that the illustration thing is the next topic Vince wanted to work on, as this is also touching the related topics mentioned further above under this issue #347

- Last Minute discounts considered directly on front page/in search result list and property details page and not only after adding a accommodation unit on the booking form site #310

and

- Enhanced Property List  Totals - Consideration of last minute and/or wise price settings #291

So Vince, thank you very much! Well done! I think this is on a good way!

Best wishes,
René

**Comment by ReneCB** [comment]
P.S.: I think it would help a lot to have the option to "calculate"/see the final prices per room - which is currently only possible on the booking (form) page - already on the property details page as many users are afraid to click on "book now" (+ the obstacle that they then first have to accept the GDPR policy). From phone calls I know that they are afraid that they start to book already (and actually just want to find out what the final price is). This is from my point of view the most important usability issue which Jomres/Leohtian is currently facing resulting in lost bookings (users who leave the page as they do not see the final price and do not want to accept the GDPR/leave data since they have not decided to book yet) and "avoidable" emails to answer price requests which result from the fact that the final prices are not visible on the property details page.

**Comment by nine007** [comment]
Good day

The whole idea is to make the tariffs for rooms as easy and straight forward as possible, splitting up the tariffs with surcharges and so on does no feel logical for the property owner who is listing the property, for us as website owners it may be ok but not for people listing their properties, we get this type if complain for property owners on a daily basis and then we end up listing their property for them.

Surcharges for individual rooms alone does not work, we also need to keep in mind per person per night per room, that means that we need to add surcharges per person per room also when there is more than one person in a room and the tariffs are set pppn and not only just for the unit or room.

I do not agree that the dropdown box in my picture will result in more room types. I think doing it this way will allow me to disable the "allow managers to create more room types".  This way we do not have to add more room types and we can set prices to the room name of the selected room type in the tariffs, if we need to add surcharges we can just add it as an extra under settings.

or we can have an "yes or no" option in tariffs asking if the tariff should be linked to a room or not and if yes then a dropdown box appear with a list of room names that is linked to the current room/resource type. (just a thought)

I do know this is only experimental, and I do appreciate everyone's input and Vince hard work, thank you.

**Comment by ReneCB** [comment]
Two questions nine007: 
Imagine you have a hotel with apartment hotel with 100 apartments and 4 or more different prices for a 2 bedroom apartment based on whether they have sea view, are on top floor, close to the pool, ...
So let us say there is one room type with a number of different prices and quite a number of rooms. How should this work with your dropdown solution? How do you want to solve the allocation of rooms to prices with dropdowns? 

Anyway if Vince thinks this is better to implement this under "Tariffs" I do not have a problem with it but I am not sure if the is more easy to anyone. I think only a matrix would make sense there (if this should be implemented under "Tariffs"). Depending on the number of different prices and rooms of the same room type this can become quite a large matrix... I think the individual surcharge optionn per room (as Vince made is not) is more "elegant" there. 

I think this topic is more "connected" with "rooms" than with "Extras" where I would only expect something that I can book in addition to the room. 

And yes, I agree - if you run a portal you normally disable the "allow managers to create more room types" as this will end up in chaos in the filters.

**Comment by nine007** [comment]
Thank you ReneCB for your clear explanation, I understand your dilemma better now, and yes, I also have that problem with big loges.

I just want this to be an easy way for property owners to be able to add prices to individual rooms and not only room types.

The reason I am thinking it would make more sense to add it to tariffs it that we and property owners only have to go to one place to add or edit tariffs and not have to think of different places to add or edit tariffs or split one tariff in different locations, to translate this to property owners will be a nightmare, and they all will complain. And also still have the ability to set the room price to per room or per person per room if it is in tariffs. The dropdown I used as an example is only a suggestion, I am sure something better can be done.

We are currently working with 2 channel management companies and we need property owners to configure individual room prices as per room or as per person per room..
http://site.nightsbridge.com/channel-management/
https://www.htihospitality.tech/channel-management/

**Comment by JeromePayan** [comment]
here a AIRBNB screenshot
![basicprice airnb](https://user-images.githubusercontent.com/25484155/51025634-e306f700-158c-11e9-91b5-0c7d16bf2da0.PNG)

**Comment by ReneCB** [comment]
Vince, I am sure you are happy to see this lively discussion ;-) 

I actually think that the tariff configuration in Jomres basically gives a lot of options which I like (especially in Tariff Configuration Mode: Micromanage). 

nine007: I agree that we should try to make it as simple as possible.

The biggest tariff related issue that we currently facing in Jomres is that we need to add a complete additional tariff for an extra person which is too complicated/could be solved easier. This is addresses by 
Basic pricing for renting #251

Concerning the discussion from today I think we should follow this idea with a basic tariff that can be "adjusted" like the other OTAs have it. We already have the JPD discounts from Rodrigo for discount/length of stay adjustments. We also have the last minute/wise price feature under property configuration (which I would actually move one level up in the navigation/hierarchy so that it is easy to find directly under "Settings" and not hide this under "property configuration" as it is a great feature which the clients like). By the way: mabye "Tariffs", "Last minute/wise price", "(JPD) discounts" and "Discount Coupons" could also be grouped).

@ nine007: By the way: As you see actually currently the PMs also do not find all pricing related issues under "Settings" -> "Tariffs" as "Last minute/wise price", "discounts"... are separated from the "tariff".

To follow the "one basic tariff" per room type idea that can be adjusted, it would - from my point of view - make sense to follow the idea Vince was pursuing with the "Experimental feature for #337 Surcharges for individual rooms") with offering price adjustments per individual room (which is currently / experimental under "rooms") as otherwise some sorting feature (matrix) would be required if you think intensively about it. Naturally Vince could also extract the currently experimental "room surcharge" feature from "Rooms" and move it whereever he likes (if you do not like it under "rooms" something like "price adjustments by rooms" could maybe be created). Currently I think the way Vince implemented it is the best option, as placing it under tariffs (with or without a "dropdown" method to allocate a number of rooms (same room type) to a price) would either result in the creation of more than one basic tariff for a room type or - in order to give the option to make price adjustments for a room type on an individual room level - the "listing" that we have currently under "rooms" at least partly would have to be duplicated (if it should be under "Tariffs" and not "Rooms") in order to be able to make price adjustments on a (individual) room level. From my point of view this creates redundancies which are not elegant (as the long sentense before ;-)). If the PM starts setting up the rooms first and enters the tariffs/prices later in the setup process he would/could also see easily that there are configuration option for the price already when he is setting up the rooms.

Vince - maybe you could comment on what you think is feasible. Because I think it is also important to keep in mind that the changes will have to be done in running systems and what programming effort this means for you...

Thank you for the lively discussion,
René

**Comment by jomres** [comment]
I'm loving the conversation. Trouble is Real Life is intruding so I'm trying to do tickets, read this and housework all at the same time.  

I could murder a cup of tea.

I'm going to let this conversation evolve a bit more. If you'all can arrive at a consensus I'll do my damnedest to write what you want providing it doesn't become a monstrosity to maintain. The booking engine is already extremely complex, I'm just a simple code monkey, I don't want to make it even worse :D

**Comment by nine007** [comment]
Good day

hope all is well.

I do now that Tariffs like "Last minute/wise price", "discounts are in a separate location, I do not mind that at all, it makes sense that it should be in a different category.

We have spend hours on the big commercial sites to see how they deal with per room charges, and I could see that they do not charge per room/resource type, but only per room or per person per room.

So the 2 screenshots below is how we think it's logical and easy for the PM to add/edit tariffs, on the first screenshot you can see that the room is charge as a whole unit. and on the second screenshot you can see that the room is charges per person sharing. Now the reason that the per person sharing looks like that is the PM's do not want to charge per person sharing on a singe tariff, from our experience they always have fixed prices based on the amount of adults, we saw that some has 6 tariffs fields and some has up to 8, and then we also need to remember the children tariffs, Many PM's also do not allow children in a room, or only children above certain age.

I hope this makes sense.

![room tariff for whole unit](https://user-images.githubusercontent.com/1021432/51179563-92660580-18ce-11e9-84b9-8ee83edc6eeb.png)

![room tariff for per person per night](https://user-images.githubusercontent.com/1021432/51179574-9b56d700-18ce-11e9-923a-b780b480e570.png)

**Comment by nine007** [comment]
Good day

hope all is well.  just would like to know if there is any update on tariffs per room like my screenshots above?  We also constantly are getting properties that have "child policies" this means that some rooms do not allow children, some rooms only allow babies, and some rooms only allow children above a certain age.  With the current setup of guest types we cannot setup child policies correctly, so unfortunately we are loosing clients every day because of the inability to set tariffs per room or per person per room and child policies.

We are also working on to integrate eRes, https://www.htihospitality.tech/channel-management into Jomres, but are stuck because of the current difficulties.

Jomres is by far the best system, and I will not go to other systems because of their lack of features, I really love Jomres. This is the only thing that Jomres lack.

thank you

**Comment by jomres** [comment]
> we are loosing clients every day because of the inability to set tariffs per room or per person per room and child policies.

How many other people are seeing this?

**Comment by ReneCB** [comment]
Dear Vince, 

a higher priority for me would have (mentioned further above):

- Last Minute discounts considered directly on front page/in search result list and property details page and not only after adding a accommodation unit on the booking form site #310

- Enhanced Property List Totals - Consideration of last minute and/or wise price settings #291

Otherwise nearly nobody is aware of the great feature "Last Minute discounts" which many owners like but currently they are very dissapointed that the last minute prices are NOT considered on the search results list but only AFTER clicking on book now.

Thank you for consideration + best wishes,

René
