### ISSUE TITLE
Amend Booking - Classic Rooms

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#364]
9.16.1

With the following configuration:
Rooms list style=Classic
Available rooms/tariff limit = 1 
Tariff Configuration Mode = Advanced
Tariffs = 24 Tariff's using min-max days to create weekly tariffs (1-7=tariff1, 8-14=tariff2,15-21=tariff3 etc) 
Rooms = 32
Guest Types not used

When making a booking 1 Tariff is displayed based upon the number of days selected 
Eg 7 days selected will display 1 room at tariff 1

When Amend Booking is used, the 32 rooms are automatically displayed of the original tariff. 
If the amend action is to change the days to 14, then 32 rooms are displayed of tariff 2. 

Issue is that the new booking process is smooth and the amend booking process is unnecessarily displaying too many rooms of the same tariff.

**Comment by jomres** [comment]
That was a feature request, Ally, from a previous user. They wanted the freedom, as a manager, to choose the right room for their requirements. This is different to the normal booking engine process where only a (configurable) number of rooms of a certain type/tariff combo would be offered.

In other words, it's designed to work that way so that managers can move guests to different specific rooms.
