### ISSUE TITLE
Dropdown Property list available in Normal View Template

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#374]
Vince

In the Property Management Dasboard
With Full Screen mode template there is a dropdown properties list available... (sooooo usefull)
Can we have the same in a Normal Mode template ?

And what do you think if Jomres could STAY in the same module  (tariff, description...) as soon we switch to an other property ? For exemple, if i want to configure the same information to all my properties i will just need to switch to another property... (can make save some lot of click)

Jérôme

**Comment by jomres** [comment]
1. No, we don't have that in because of responsiveness reasons. You're free however to copy the code from one template to another, the array variable is still available to the template that doesn't show that output, but it's simply not coded into that particular template file itself.

2. Please use the clone property feature Jerome.
