### ISSUE TITLE
Use CSS Stripes for property feature images

### ISSUE THREAD

**Issue by joejoe2010** [WoollyinWalesIT/jomres#395]
Hi,
this issue is related with my previous one #394 about perfomance.
But as it doesn't occur on all pages by default directly on the homescreen but later when showing details of a property I decided to create an extra issue.

The problem is that each property feature image (like http://joomla-portal.jomres.net/jomres/uploadedimages/pfeatures/airport_nearby.png) is loaded extra from the server. And if many of them are loaded which is sometimes the case than script execution is paused until the requests are finished AFAIK / IMHO ;-)

It would be much better for performance if the pfeature-images were combinded in a so called CSS sprite (see eg. [https://www.w3schools.com/Css/css_image_sprites.asp](https://www.w3schools.com/Css/css_image_sprites.asp))

Do you think it would be possible to adapt jomres so that CSS sprites are used?

Hint: This problem can also be seen on gtmetrix.com when activating the pfeatures in the home-screen module on joomla.
Hint2: If you can't access the above gtmetrix analysis link just request an own analysis. ;-)

Thanks
joejoe2010

**Comment by joejoe2010** [comment]
Link issue to #394

**Comment by jomres** [comment]
I've always been reluctant to work with sprites because the current method of doing things makes it easy for users to create new images and upload them. Sprites are another kettle of fish altogether and I think it's beyond most users. Users are familiar with the concept of uploading images and assigning them to resources, and while yes they create overhead, it's a trade off that I think most people will make. Making sprites adds a level of complexity to the image handling functionality.

I'm always willing however to listen to the community.
