### ISSUE TITLE
Add price multiplier for each microtariff management (inflation factor)

### ISSUE THREAD

**Issue by joniale** [WoollyinWalesIT/jomres#397]
Dear Jomres developers,

Most of the time the owners and managers have to increase the price of the accommodations each year according to the **inflation**. It would be good to have an easy way to define **a factor multiplier** so that we increase the calculated end price without having to do it manually on each tariff. 
(maybe 2 factors 1 for property and 1 for specific tariff which will be default "1")

Would that be possible?
Best regards,

**Comment by joniale** [comment]
For clarification. This factor or multiplier is a one time event.  In other words, it is equivalent to read the price for a day, multiply it by the factor and then write the new value of the price on that day. This will be done for all the prices defined on the tariff.  The advantage of this procedure in comparison of doing that manually is that if you have several special prices on some dates they will be proportionally modified by the factor too.

**Comment by ReneCB** [comment]
Actually I am not sure if the feature as described above is really as helpful as you currently think as from my experirence as portal operator most PMs operate with round prices (often ending with 9) without decimal places which you would normally receive by just adjusting for inflation in the way you described above. I would prefer a feature like "copy prices from current year to next year". For this (as for your feature request) Vince would need to store the prices for at least the last 365 nights (better the whole last year before the current year) for all accommodations in the database. Currently all prices in the past "are gone" which in my opinion is a disadvantage, because you can't always remember afterwards which prices were set / worked best. From a technical point of view I think it would be easy to combine a feature like "copy prices from current year to next year" with "and adjust (multiply) the prices by factor X.Y" that you request. And if I think about it maybe also with "please round up/down to whole EUR amounts".

Thank you anyway for opening this discussion as I agree that there should be a simple way to transfer the prices from one season to the next with easy adjustment features.
Best regards
René

**Comment by joniale** [comment]
I understand your point. All this could be solved with my other feature request https://github.com/WoollyinWalesIT/jomres/issues/396#issue-430076536.
I think a script with the API would solve all these problems and would be very easy. The API already exists so we only need 2 buttons (edit and run script) , and php code examples using the API (which is not complex). To read a date price for a tariffs and modifying it would be easy with the API.

Anyway, this requests is something that will solve only specific usage cases.
I have not thought about the case where nothing was defined so your idea of taking one year from a specific day and copying to the future with a factor modification looks good. The user only have to **clone** the prices by clicking on that button.
Still there will be problems with this feature because "this cloning" do not recognize special dates completely. What i mean is that if one user wrote a special price on **eastern** then the next year eastern will not be on the same date.  It is a trade off between easy to use and configurability.
Therefore, i think it much important to develop my other API suggestion.

**Comment by jomres** [comment]
Insufficient support for feature request.
