### ISSUE TITLE
No-Show reservation status  ?

### ISSUE THREAD

**Issue by IEDfactory** [WoollyinWalesIT/jomres#422]
Hi,

Is it possible to predict the No-Show status in the next version of Jomres? It is an important statut for both exports and hotel managers.

Thanks in DAvance

**Comment by jomres** [comment]
I've been thinking about this, and I have a solution which will benefit everybody.

The problem with No Shows is that there's not much you can do with limited data. 

Let me explain.

Let's say that there is a problem guest who "No Shows" at lots of different properties. If that guest has never failed to turn up at your property, or on your website, then you wont know that they are a risky booking until the day. 

Now, it's quite possible to collect No Show information within Jomres itself, it really only requires development of the feature, so at least when they've done it once, you can be warned a second time. The chances of that, however, are very small, meaning that your risk really remains the same.

Ok, so that's the limited data problem. What's a possible solution?

[The Jomres Syndication Network.](https://www.jomres.net/features/jomres-syndication-network)

As I'm sure you're aware by now, the JSN has been rolled out into the most recent versions of the system. It's functioning well, so it makes sense now to see if we can use the Network in more inventive ways and one way that I thought of was if we were to log No Shows on the [App server](https://www.jomres.net/manual/developers-guide-2/387-jomres-syndication-network) then we could share that knowledge across the whole network of Jomres sites.

**Comment by IEDfactory** [comment]
Hi Vince, happy to hear from you.
I have not forgotten you, but in the last two months I have had a lot of work away from Jomres. Projects are one thing, financial reality is another! So I worked on the creation of site by leaving a little RevPar with Jomres aside ...
I do not quite understand your answer, and I wonder if we're talking about the same thing? The Noswhow is just one more booking status, like Arrived, Confirmed, Canceled, etc ...
This is a customer who has booked, paid a deposit and does not show up the day of his arrival ...
Excuse me Vince, but I do not understand your answer: can you complete that?
Best regards.
Stéphane

**Comment by jomres** [comment]
https://github.com/WoollyinWalesIT/jomres/commit/8d07b8165f427bae79f671b7514de18167ad3c9c

**Comment by jomres** [comment]
No shows are a risk to all booking managers/hosts because it makes the room/property unavailable on dates when it otherwise would have been available, therefore I decided that when a booking is marked as No Show, we need to update the app server with a unique identifier for that guest (no personal data is stored, just a cryptographically safe hash of their email, even I can't decode it) which currently records the number of bookings somebody using that email address has made and the number of times their bookings have been marked as "No Show".

**Comment by jomres** [comment]
Todo : Make it so that property managers can see the Booking v the No Show numbers in the edit booking page.

**Comment by IEDfactory** [comment]
Great ! thank you Vince for your listening!
This feature is in the Nightly version I guess?
Where exactly is the language file?
Best regards
Stéphane

**Comment by jomres** [comment]
> This feature is in the Nightly version I guess?

It will be when I've done some more testing. 

Keep an eye on https://github.com/WoollyinWalesIT/jomres/commits/nightly

> Where exactly is the language file?

https://github.com/WoollyinWalesIT/jomres/tree/nightly/language

**Comment by IEDfactory** [comment]
Thanks about there informations, I've added in my RSS Feedly...
Best regards

**Comment by jomres** [comment]
The feature is now complete. I've done some tests and it seems to be working as expected but as always there will be edge-cases/unanticipated issues that always crop up in new features.

Users can help testing new features by [installing the Nightly](https://www.jomres.net/manual/installation-and-upgrading-2/370-installing-updating-to-the-nightly-branch) before it's released as a new version.
