### ISSUE TITLE
iCal Feed From Other Source, e.g. HomeAway/VRBO

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#46]
https://www.jomres.net/forum/Feature-requests/24876-ical-feed-from-other-source-e-g-homeaway-vrbo

I'd like to be able to have HomeAway/VRBO's calendar feed into Jomres.

Having this feature will make enticing the ability to move off of HomeAway/Vrbo (now Expedia) as concurrent accounts can be had and the migration away form those services to Jomres less painful.

**Comment by joniale** [comment]
+1 to this feature.
iCal import URL feed from external sources is a very important feature for many small proprietaries.

Most of the small proprietaries which have pensions and small business by their own, use manual synchronization or iCal when it is supported in the other booking portals. They all hate to do it manually because of the big work of being always connected and worried about double reservations from different portals. When iCal was introduced in some booking systems that feature was a release for many owners, because many owners centralized their small management in one place (google). They could have an overview of collisions and act only when a problem came in one place. A reservation email come to gmail and the user can block on calendar which is exported to other reservation system automatically through ical. (most of those ical portals support import URL feed!)
For small business that uses jomres, i think they are many will be very happy to have that option.

Many portals are introducing ical as standard, and they support BOTH directions and not only export.
https://help.homeaway.com/articles/How-do-I-import-my-iCal-or-Google-calendar
https://rentalsupport.tripadvisor.com/articles/FAQ/noc-How-does-calendar-sync-work
https://www.rentalsystems.com/help/how-do-i-sync-calendars
and airbnb and so on.

Centralizing all the reservation management on Jomres can be done, but if jomres doesn't support the import of that information, then this doesn't release you of looking to other reservation portals.
There is still not an standard to do this synchronization between booking systems/portals, therefore many other companies support the service of this syncronization (the so called channel managers). So long there is no a standard and generalized way to do this, channel managers will have a piece of the market. However, i will say this will be reduced with the time if iCal go forward.   All rental business demand that standard and iCal trends seems to be the winner. Jomres should contribute to this and help their clients with this feature.

**Comment by joniale** [comment]
To avoid problems duplicating reservations. Each time an import/update is done then it should be first stored the UID (unique ID of the events) in the jomres blackreservation database. 
On the second import, it should be checked that you are not importing the same event by comparing the UID of the events.
This should be done also when you do importing from files. Currently, if you import two times the same ICS file it will try to book on that type of property the same event again if there are some rooms free.

To understand the UID you only have to edit one .ics file and see how the events are unique defined.
e.g.
BEGIN:VEVENT
DTSTART;VALUE=DATE:20161222
DTEND;VALUE=DATE:20170214
DTSTAMP:20170710T193509Z
**UID:ok07997sovlhgt292k6rb5b2io@google.com**
CREATED:20161222T190151Z
DESCRIPTION:
LAST-MODIFIED:20161222T190151Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Completo de un dormitorio
TRANSP:OPAQUE
END:VEVENT

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Privisional functionality for this has been developed, who wants to play with the new code?

**Comment by jomres** [comment]
I should note that right now this is for MRPs only, SRPs will come later.

**Comment by joniale** [comment]
Cool, great news! how can i test the code?

**Comment by jomres** [comment]
Raise a ticket Rene, I'll send you a copy of the plugin, just use the 3rd party plugin installer in Jomres to upload it.

**Comment by jomres** [comment]
Just checked this with an SRP, it'll work fine but the language is slightly confusing because it still refers to rooms and gives you a dropdown with just one option in it (like the file upload version does).

**Comment by jomres** [comment]
The new version of the ical plugin has been added to the plugin manager, any questions about that plugin, please create a new issue. I'll close this now.
